<?php

namespace Progetto\Entity\Repository;

/**
 * ProdottiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgettoRepository extends \Doctrine\ORM\EntityRepository
{
}
